SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE '/Users/martinlulgjuraj/Downloads/company/dependent.dat'
INTO TABLE dependent
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

SET FOREIGN_KEY_CHECKS = 1;